source 'https://rubygems.org'
gem 'rails', '4.2.3'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'actionpack-action_caching'
gem 'rails-observers'
gem 'will_paginate'
gem 'turbolinks'
gem 'figaro'

group :development, :test do
  gem 'newrelic_rpm'
  gem 'pry'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'fabrication'
  gem 'faker'
  gem 'rspec-rails', '~> 3.3.3'
  gem 'bullet'
end
